### ISSUE TITLE
access-token rejected saying "the request could not be verified"

### ISSUE THREAD

**Issue by pkrajanand** [XeroAPI/Xero-Postman#4]
I get the oauth_verifier through request-token request. But access-token request comes back with 401 status and message `"oauth_problem=token_rejected&oauth_problem_advice=The%20Request%20could%20not%20be%20verified".` 

I have confirmed that consumer-key & consumer-secret of my public account, are correct and valid - by logging into developer.xero.com/myapps. 

I actually tried with 2 different public accounts - both were in working condition as of last week.

I know that XERO is moving to OAuth2, but it would be greatly appreciated with any help to get around this.

**Comment by MattR-Api** [comment]
Hi @pkrajanand 

Thanks for letting us know about your issue. 

As you've mentioned that you're using Consumer Keys and Consumer Secrets, the app you're using on the My Apps page of the developer Center will be an OAuth 1.0a app and incompatible with this Postman tutorial. You'll need to create a New OAuth 2.0 app to get a Client ID and Client Secret and use those keys instead. 

If you're still having issues after generating a new OAuth 2.0 app, please get in touch with us at api@xero.com with the new Client ID you've received and we'll be happy to assist further. 

Cheers

Matt

**Comment by pkrajanand** [comment]
Thanks Matt for your response.

Yes, you are right.. I am using consumer key & secret of of a 'public' OAuth 1.0a app from developer.xero.com/myapps - which was working perfectly fine with Postman until when I tried last on this 7th July. 

I am surprised to hear that this tutorial turned incompatible with 1.0a app keys - especially when I can still see this note from the ReadMe of this project. 

> Xero-Postman
A Postman collection for authenticating to the Xero API. Please note that this collection provides access using OAuth 1.0a. Our newer collection using OAuth 2.0 can be found here(https://github.com/XeroAPI/xero-postman-oauth2).

I have a web-application that talks to XERO using OAuth1.0a app keys. Migration to OAuth2 cannot be done immediately and we have a roadmap for that. 

I usually use PostMan to learn and verify XERO API features before I add those to my application. I tried with 2 different public 1.0a app keys- which had been working until last week. Now, it fails even with Request-Token invocation that just sends back a 401 !!! Actually this call should have redirected me to a login page after confirming the just the existence of the keys. Now, no login page is shown, so I deduce that the XERO-api does not even recognise the keys. 

Officially, XERO's deadline is until Dec 2020 for existing OAuth 1.0a apps to migrate to OAuth2 - as per this note from https://developer.xero.com/faq/migration/.

> Can I/should I still get my OAuth 1.0a app certified?
We encourage anyone building new apps to use OAuth 2.0 but we will continue to certify OAuth 1.0a integrations until the end of March 2020. Please be aware that if you choose to launch with OAuth 1.0a you will be required to migrate it to OAuth 2.0 before December 2020

So this looks more like a mistake from their side for Public apps. I have heard from a colleague that OAuth 1.0a Partner apps do not face an issue like mine.

Yea, I understand that I need to take it direct to XERO, as this Project is meant only to provide Postman setup to interact with Xero 1.0a endpoints.

Thanks for your time, greatly appreciated.

**Comment by MattR-Api** [comment]
Hi @pkrajanand 

Apologies, I had my Postman collections mixed up. 

You will be able to use the Migration endpoint, but only if your app has been through the certification process and is a Partner App. If you do have a Private or Public app, you will have to connect each Org manually to your new OAuth 2.0 app and without the use of the migration endpoint. 

As you would only have 30 minute access on Public apps in either case, you can simply provide the new OAuth 2.0 link to your users, rather than the older public app connection link. If you've included the Offline_Access scope you'll also be able to maintain a connection by refreshing your access tokens with refresh tokens. 

If you do have a Partner App, please get in touch with us at api@xero.com with its Consumer ID and we'll be happy to help diagnose any errors that may be occurring. 

Kind Regards

Matt
